export { Hero } from "./Hero";
export { HowItWorks } from "./HowItWorks";
export { Pricing } from "./Pricing";
 export { FeatureComparisonTable } from "./FeatureComparisonTable";
export { Footer } from "./Footer";
export { Navbar } from "./Navbar";
export { AlertTypes } from "./AlertTypes";
// Legacy exports (kept for reference)
export { GamesSection } from "./GamesSection";
export { AlertsSection } from "./AlertsSection";
