-- Insert team mappings for all leagues
-- Using Default logo type for all teams
-- sportsgameodds_id format: TEAM_NAME_LEAGUE (uppercase, underscores)

INSERT INTO public.teams (id, display_name, city, league, sport, logo_filename, sportsgameodds_id) VALUES
-- MLB American League Central
('white_sox_mlb', 'Chicago White Sox', 'Chicago', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=Central, Team=Chicago White Sox, Type=Default', 'CHICAGO_WHITE_SOX_MLB'),
('guardians_mlb', 'Cleveland Guardians', 'Cleveland', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=Central, Team=Cleveland Guardians, Type=Default', 'CLEVELAND_GUARDIANS_MLB'),
('tigers_mlb', 'Detroit Tigers', 'Detroit', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=Central, Team=Detroit Tigers, Type=Default', 'DETROIT_TIGERS_MLB'),
('royals_mlb', 'Kansas City Royals', 'Kansas City', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=Central, Team=Kansas City Royals, Type=Default', 'KANSAS_CITY_ROYALS_MLB'),
('twins_mlb', 'Minnesota Twins', 'Minnesota', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=Central, Team=Minnesota Twins, Type=Default', 'MINNESOTA_TWINS_MLB'),
-- MLB American League East
('orioles_mlb', 'Baltimore Orioles', 'Baltimore', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=East, Team=Baltimore Orioles, Type=Default', 'BALTIMORE_ORIOLES_MLB'),
('red_sox_mlb', 'Boston Red Sox', 'Boston', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=East, Team=Boston Red Sox, Type=Default', 'BOSTON_RED_SOX_MLB'),
('yankees_mlb', 'New York Yankees', 'New York', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=East, Team=New York Yankees, Type=Default', 'NEW_YORK_YANKEES_MLB'),
('rays_mlb', 'Tampa Bay Rays', 'Tampa Bay', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=East, Team=Tampa Bay Rays, Type=Default', 'TAMPA_BAY_RAYS_MLB'),
('blue_jays_mlb', 'Toronto Blue Jays', 'Toronto', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=East, Team=Toronto Blue Jays, Type=Default', 'TORONTO_BLUE_JAYS_MLB'),
-- MLB American League West
('astros_mlb', 'Houston Astros', 'Houston', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=West, Team=Houston Astros, Type=Default', 'HOUSTON_ASTROS_MLB'),
('angels_mlb', 'Los Angeles Angels', 'Los Angeles', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=West, Team=Los Angeles Angels, Type=Default', 'LOS_ANGELES_ANGELS_MLB'),
('athletics_mlb', 'Oakland Athletics', 'Oakland', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=West, Team=Oakland Athletics, Type=Default', 'OAKLAND_ATHLETICS_MLB'),
('mariners_mlb', 'Seattle Mariners', 'Seattle', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=West, Team=Seattle Mariners, Type=Default', 'SEATTLE_MARINERS_MLB'),
('rangers_mlb', 'Texas Rangers', 'Texas', 'MLB', 'BASEBALL', 'mlb/League=American League, Division=West, Team=Texas Rangers, Type=Default', 'TEXAS_RANGERS_MLB'),
-- MLB National League Central
('cubs_mlb', 'Chicago Cubs', 'Chicago', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=Central, Team=Chicago Cubs, Type=Default', 'CHICAGO_CUBS_MLB'),
('reds_mlb', 'Cincinnati Reds', 'Cincinnati', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=Central, Team=Cincinnati Reds, Type=Default', 'CINCINNATI_REDS_MLB'),
('brewers_mlb', 'Milwaukee Brewers', 'Milwaukee', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=Central, Team=Milwaukee Brewers, Type=Default', 'MILWAUKEE_BREWERS_MLB'),
('pirates_mlb', 'Pittsburgh Pirates', 'Pittsburgh', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=Central, Team=Pittsburgh Pirates, Type=Default', 'PITTSBURGH_PIRATES_MLB'),
('cardinals_mlb', 'St. Louis Cardinals', 'St. Louis', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=Central, Team=St.Louis Cardinals, Type=Default', 'ST_LOUIS_CARDINALS_MLB'),
-- MLB National League East
('braves_mlb', 'Atlanta Braves', 'Atlanta', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=East, Team=Atlanta Braves, Type=Default', 'ATLANTA_BRAVES_MLB'),
('marlins_mlb', 'Miami Marlins', 'Miami', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=East, Team=Miami Marlins, Type=Default', 'MIAMI_MARLINS_MLB'),
('mets_mlb', 'New York Mets', 'New York', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=East, Team=New York Mets, Type=Default', 'NEW_YORK_METS_MLB'),
('phillies_mlb', 'Philadelphia Phillies', 'Philadelphia', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=East, Team=Philadelphia Phillies, Type=Default', 'PHILADELPHIA_PHILLIES_MLB'),
('nationals_mlb', 'Washington Nationals', 'Washington', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=East, Team=Washington Nationals, Type=Default', 'WASHINGTON_NATIONALS_MLB'),
-- MLB National League West
('diamondbacks_mlb', 'Arizona Diamondbacks', 'Arizona', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=West, Team=Arizona Diamondbacks, Type=Default', 'ARIZONA_DIAMONDBACKS_MLB'),
('rockies_mlb', 'Colorado Rockies', 'Colorado', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=West, Team=Colorado Rockies, Type=Default', 'COLORADO_ROCKIES_MLB'),
('dodgers_mlb', 'Los Angeles Dodgers', 'Los Angeles', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=West, Team=Los Angeles Dodgers, Type=Default', 'LOS_ANGELES_DODGERS_MLB'),
('padres_mlb', 'San Diego Padres', 'San Diego', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=West, Team=San Diego Padres, Type=Default', 'SAN_DIEGO_PADRES_MLB'),
('giants_mlb', 'San Francisco Giants', 'San Francisco', 'MLB', 'BASEBALL', 'mlb/League=National League, Division=West, Team=San Francisco Giants, Type=Default', 'SAN_FRANCISCO_GIANTS_MLB'),

-- NBA Eastern Conference
('hawks_nba', 'Atlanta Hawks', 'Atlanta', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Atlanta Hawks, Alt=Default', 'ATLANTA_HAWKS_NBA'),
('celtics_nba', 'Boston Celtics', 'Boston', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Boston Celtics, Alt=Default', 'BOSTON_CELTICS_NBA'),
('nets_nba', 'Brooklyn Nets', 'Brooklyn', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Brooklyn Nets, Alt=Default', 'BROOKLYN_NETS_NBA'),
('hornets_nba', 'Charlotte Hornets', 'Charlotte', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Charlotte Hornets, Alt=Default', 'CHARLOTTE_HORNETS_NBA'),
('bulls_nba', 'Chicago Bulls', 'Chicago', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Chicago Bulls, Alt=Default', 'CHICAGO_BULLS_NBA'),
('cavaliers_nba', 'Cleveland Cavaliers', 'Cleveland', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Cleveland Cavaliers, Alt=Default', 'CLEVELAND_CAVALIERS_NBA'),
('pistons_nba', 'Detroit Pistons', 'Detroit', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Detroit Pistons, Alt=Default', 'DETROIT_PISTONS_NBA'),
('pacers_nba', 'Indiana Pacers', 'Indiana', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Indiana Pacers, Alt=Default', 'INDIANA_PACERS_NBA'),
('heat_nba', 'Miami Heat', 'Miami', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Miami Heat, Alt=Default', 'MIAMI_HEAT_NBA'),
('bucks_nba', 'Milwaukee Bucks', 'Milwaukee', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Milwaukee Bucks, Alt=Default', 'MILWAUKEE_BUCKS_NBA'),
('knicks_nba', 'New York Knicks', 'New York', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=New York Knicks, Alt=Default', 'NEW_YORK_KNICKS_NBA'),
('magic_nba', 'Orlando Magic', 'Orlando', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Orlando Magic, Alt=Default', 'ORLANDO_MAGIC_NBA'),
('76ers_nba', 'Philadelphia 76ers', 'Philadelphia', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Philadephia 76ers, Alt=Default', 'PHILADELPHIA_76ERS_NBA'),
('raptors_nba', 'Toronto Raptors', 'Toronto', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Toronto Raptors, Alt=Default', 'TORONTO_RAPTORS_NBA'),
('wizards_nba', 'Washington Wizards', 'Washington', 'NBA', 'BASKETBALL', 'nba/Conference=Eastern, Team=Washington Wizards, Alt=Default', 'WASHINGTON_WIZARDS_NBA'),
-- NBA Western Conference
('mavericks_nba', 'Dallas Mavericks', 'Dallas', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Dallas Mavericks, Alt=Default', 'DALLAS_MAVERICKS_NBA'),
('nuggets_nba', 'Denver Nuggets', 'Denver', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Denver Nuggets, Alt=Default', 'DENVER_NUGGETS_NBA'),
('warriors_nba', 'Golden State Warriors', 'Golden State', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Golden State Warriors, Alt=Default', 'GOLDEN_STATE_WARRIORS_NBA'),
('rockets_nba', 'Houston Rockets', 'Houston', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Houston Rockets, Alt=Default', 'HOUSTON_ROCKETS_NBA'),
('clippers_nba', 'LA Clippers', 'Los Angeles', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=LA Clippers, Alt=Default', 'LOS_ANGELES_CLIPPERS_NBA'),
('lakers_nba', 'Los Angeles Lakers', 'Los Angeles', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Los Angles Lakers, Alt=Default', 'LOS_ANGELES_LAKERS_NBA'),
('grizzlies_nba', 'Memphis Grizzlies', 'Memphis', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Memphis Grizzlies, Alt=Default', 'MEMPHIS_GRIZZLIES_NBA'),
('timberwolves_nba', 'Minnesota Timberwolves', 'Minnesota', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Minnesota Timberwolves, Alt=Default', 'MINNESOTA_TIMBERWOLVES_NBA'),
('pelicans_nba', 'New Orleans Pelicans', 'New Orleans', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=New Orleans Pelicans, Alt=Default', 'NEW_ORLEANS_PELICANS_NBA'),
('thunder_nba', 'Oklahoma City Thunder', 'Oklahoma City', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Oklahoma City Thunder, Alt=Default', 'OKLAHOMA_CITY_THUNDER_NBA'),
('suns_nba', 'Phoenix Suns', 'Phoenix', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Phoenix Suns, Alt=Default', 'PHOENIX_SUNS_NBA'),
('blazers_nba', 'Portland Trail Blazers', 'Portland', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Portland Trailblazers, Alt=Default', 'PORTLAND_TRAIL_BLAZERS_NBA'),
('kings_nba', 'Sacramento Kings', 'Sacramento', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Sacramento Kings, Alt=Default', 'SACRAMENTO_KINGS_NBA'),
('spurs_nba', 'San Antonio Spurs', 'San Antonio', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=San Antonio Spurs, Alt=Default', 'SAN_ANTONIO_SPURS_NBA'),
('jazz_nba', 'Utah Jazz', 'Utah', 'NBA', 'BASKETBALL', 'nba/Conference=Western, Team=Utah Jazz, Alt=Default', 'UTAH_JAZZ_NBA'),

-- NFL AFC East
('bills_nfl', 'Buffalo Bills', 'Buffalo', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=East, Team=Buffalo Bills', 'BUFFALO_BILLS_NFL'),
('dolphins_nfl', 'Miami Dolphins', 'Miami', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=East, Team=Miami Dolphines', 'MIAMI_DOLPHINS_NFL'),
('patriots_nfl', 'New England Patriots', 'New England', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=East, Team=New England Patriots', 'NEW_ENGLAND_PATRIOTS_NFL'),
('jets_nfl', 'New York Jets', 'New York', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=East, Team=New York Jets', 'NEW_YORK_JETS_NFL'),
-- NFL AFC North
('ravens_nfl', 'Baltimore Ravens', 'Baltimore', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=North, Team=Baltimore Ravens', 'BALTIMORE_RAVENS_NFL'),
('bengals_nfl', 'Cincinnati Bengals', 'Cincinnati', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=North, Team=Cincinatti Bengals', 'CINCINNATI_BENGALS_NFL'),
('browns_nfl', 'Cleveland Browns', 'Cleveland', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=North, Team=Cleveland Browns', 'CLEVELAND_BROWNS_NFL'),
('steelers_nfl', 'Pittsburgh Steelers', 'Pittsburgh', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=North, Team=Pittsburgh Steelers', 'PITTSBURGH_STEELERS_NFL'),
-- NFL AFC South
('texans_nfl', 'Houston Texans', 'Houston', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=South, Team=Houston Texans', 'HOUSTON_TEXANS_NFL'),
('colts_nfl', 'Indianapolis Colts', 'Indianapolis', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=South, Team=Indianapolis Colts', 'INDIANAPOLIS_COLTS_NFL'),
('jaguars_nfl', 'Jacksonville Jaguars', 'Jacksonville', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=South, Team=Jacksonville Jaguars', 'JACKSONVILLE_JAGUARS_NFL'),
('titans_nfl', 'Tennessee Titans', 'Tennessee', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=South, Team=Tennessee Titans', 'TENNESSEE_TITANS_NFL'),
-- NFL AFC West
('broncos_nfl', 'Denver Broncos', 'Denver', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=West, Team=Denver Broncos', 'DENVER_BRONCOS_NFL'),
('chiefs_nfl', 'Kansas City Chiefs', 'Kansas City', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=West, Team=Kansas City Chiefs', 'KANSAS_CITY_CHIEFS_NFL'),
('chargers_nfl', 'Los Angeles Chargers', 'Los Angeles', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=West, Team=LA Chargers', 'LOS_ANGELES_CHARGERS_NFL'),
('raiders_nfl', 'Las Vegas Raiders', 'Las Vegas', 'NFL', 'FOOTBALL', 'nfl/Conference=AFC, Division=West, Team=Las Vegas Raiders', 'LAS_VEGAS_RAIDERS_NFL'),
-- NFL NFC East
('cowboys_nfl', 'Dallas Cowboys', 'Dallas', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=East, Team=Dallas Cowboys', 'DALLAS_COWBOYS_NFL'),
('giants_nfl', 'New York Giants', 'New York', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=East, Team=New York Giants', 'NEW_YORK_GIANTS_NFL'),
('eagles_nfl', 'Philadelphia Eagles', 'Philadelphia', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=East, Team=Philadelphia Eagles', 'PHILADELPHIA_EAGLES_NFL'),
('commanders_nfl', 'Washington Commanders', 'Washington', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=East, Team=Washington Commanders', 'WASHINGTON_COMMANDERS_NFL'),
-- NFL NFC North
('bears_nfl', 'Chicago Bears', 'Chicago', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=North, Team=Chicago Bears', 'CHICAGO_BEARS_NFL'),
('lions_nfl', 'Detroit Lions', 'Detroit', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=North, Team=Detroit Lions', 'DETROIT_LIONS_NFL'),
('packers_nfl', 'Green Bay Packers', 'Green Bay', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=North, Team=Green Bay Packers', 'GREEN_BAY_PACKERS_NFL'),
('vikings_nfl', 'Minnesota Vikings', 'Minnesota', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=North, Team=Minnesota Vikings', 'MINNESOTA_VIKINGS_NFL'),
-- NFL NFC South
('falcons_nfl', 'Atlanta Falcons', 'Atlanta', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=South, Team=Atlanta Falcons', 'ATLANTA_FALCONS_NFL'),
('panthers_nfl', 'Carolina Panthers', 'Carolina', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=South, Team=Carolina Panthers', 'CAROLINA_PANTHERS_NFL'),
('saints_nfl', 'New Orleans Saints', 'New Orleans', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=South, Team=New Orleans Saints', 'NEW_ORLEANS_SAINTS_NFL'),
('buccaneers_nfl', 'Tampa Bay Buccaneers', 'Tampa Bay', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=South, Team=Tampa Bay Buccaneers', 'TAMPA_BAY_BUCCANEERS_NFL'),
-- NFL NFC West
('cardinals_nfl', 'Arizona Cardinals', 'Arizona', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=West, Team=Arizona Cardinals', 'ARIZONA_CARDINALS_NFL'),
('rams_nfl', 'Los Angeles Rams', 'Los Angeles', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=West, Team=LA Rams', 'LOS_ANGELES_RAMS_NFL'),
('49ers_nfl', 'San Francisco 49ers', 'San Francisco', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=West, Team=San Francisco 49ers', 'SAN_FRANCISCO_49ERS_NFL'),
('seahawks_nfl', 'Seattle Seahawks', 'Seattle', 'NFL', 'FOOTBALL', 'nfl/Conference=NFC, Division=West, Team=Seattle Seahawks', 'SEATTLE_SEAHAWKS_NFL'),

-- NHL Eastern Atlantic
('bruins_nhl', 'Boston Bruins', 'Boston', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Atlantic, Team=Boston Bruins', 'BOSTON_BRUINS_NHL'),
('sabres_nhl', 'Buffalo Sabres', 'Buffalo', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Atlantic, Team=Buffalo Sabres', 'BUFFALO_SABRES_NHL'),
('red_wings_nhl', 'Detroit Red Wings', 'Detroit', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Atlantic, Team=Detroit Red Wings', 'DETROIT_RED_WINGS_NHL'),
('panthers_nhl', 'Florida Panthers', 'Florida', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Atlantic, Team=Florida Panthers', 'FLORIDA_PANTHERS_NHL'),
('canadiens_nhl', 'Montreal Canadiens', 'Montreal', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Atlantic, Team=Montreal Canadiens', 'MONTREAL_CANADIENS_NHL'),
('senators_nhl', 'Ottawa Senators', 'Ottawa', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Atlantic, Team=Ottawa Senators', 'OTTAWA_SENATORS_NHL'),
('lightning_nhl', 'Tampa Bay Lightning', 'Tampa Bay', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Atlantic, Team=Tampa Bay Lightning', 'TAMPA_BAY_LIGHTNING_NHL'),
('maple_leafs_nhl', 'Toronto Maple Leafs', 'Toronto', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Atlantic, Team=Toronto Maple Leafs', 'TORONTO_MAPLE_LEAFS_NHL'),
-- NHL Eastern Metropolitan
('hurricanes_nhl', 'Carolina Hurricanes', 'Carolina', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Metropolitan, Team=Carolina Hurricanes', 'CAROLINA_HURRICANES_NHL'),
('blue_jackets_nhl', 'Columbus Blue Jackets', 'Columbus', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Metropolitan, Team=Columbus Blue Jackes', 'COLUMBUS_BLUE_JACKETS_NHL'),
('devils_nhl', 'New Jersey Devils', 'New Jersey', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Metropolitan, Team=New Jersey Devils', 'NEW_JERSEY_DEVILS_NHL'),
('islanders_nhl', 'New York Islanders', 'New York', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Metropolitan, Team=New York Islanders', 'NEW_YORK_ISLANDERS_NHL'),
('rangers_nhl', 'New York Rangers', 'New York', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Metropolitan, Team=New York Rangers', 'NEW_YORK_RANGERS_NHL'),
('flyers_nhl', 'Philadelphia Flyers', 'Philadelphia', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Metropolitan, Team=Philadelphia Flyers', 'PHILADELPHIA_FLYERS_NHL'),
('penguins_nhl', 'Pittsburgh Penguins', 'Pittsburgh', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Metropolitan, Team=Pittsburgh Penguins', 'PITTSBURGH_PENGUINS_NHL'),
('capitals_nhl', 'Washington Capitals', 'Washington', 'NHL', 'HOCKEY', 'nhl/Conference=Eastern, Division=Metropolitan, Team=Washington Capitals', 'WASHINGTON_CAPITALS_NHL'),
-- NHL Western Central
('coyotes_nhl', 'Arizona Coyotes', 'Arizona', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Central, Team=Arizona Coyotes', 'ARIZONA_COYOTES_NHL'),
('blackhawks_nhl', 'Chicago Blackhawks', 'Chicago', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Central, Team=Chicago Blackhawks', 'CHICAGO_BLACKHAWKS_NHL'),
('avalanche_nhl', 'Colorado Avalanche', 'Colorado', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Central, Team=Colorado Avalanches', 'COLORADO_AVALANCHE_NHL'),
('stars_nhl', 'Dallas Stars', 'Dallas', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Central, Team=Dallas Stars', 'DALLAS_STARS_NHL'),
('wild_nhl', 'Minnesota Wild', 'Minnesota', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Central, Team=Minnesota Wild', 'MINNESOTA_WILD_NHL'),
('predators_nhl', 'Nashville Predators', 'Nashville', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Central, Team=Nashville Predators', 'NASHVILLE_PREDATORS_NHL'),
('blues_nhl', 'St. Louis Blues', 'St. Louis', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Central, Team=St.Louis Blues', 'ST_LOUIS_BLUES_NHL'),
('jets_nhl', 'Winnipeg Jets', 'Winnipeg', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Central, Team=Winnipeg Jets', 'WINNIPEG_JETS_NHL'),
-- NHL Western Pacific
('ducks_nhl', 'Anaheim Ducks', 'Anaheim', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Pacific, Team=Anaheim Ducks', 'ANAHEIM_DUCKS_NHL'),
('flames_nhl', 'Calgary Flames', 'Calgary', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Pacific, Team=Calgary Flames', 'CALGARY_FLAMES_NHL'),
('oilers_nhl', 'Edmonton Oilers', 'Edmonton', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Pacific, Team=Edmonton Oilers', 'EDMONTON_OILERS_NHL'),
('kings_nhl', 'Los Angeles Kings', 'Los Angeles', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Pacific, Team=LA Kings', 'LOS_ANGELES_KINGS_NHL'),
('sharks_nhl', 'San Jose Sharks', 'San Jose', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Pacific, Team=San Jose Sharks', 'SAN_JOSE_SHARKS_NHL'),
('kraken_nhl', 'Seattle Kraken', 'Seattle', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Pacific, Team=Seattle Kraken', 'SEATTLE_KRAKEN_NHL'),
('canucks_nhl', 'Vancouver Canucks', 'Vancouver', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Pacific, Team=Vancouver Canucks', 'VANCOUVER_CANUCKS_NHL'),
('golden_knights_nhl', 'Vegas Golden Knights', 'Las Vegas', 'NHL', 'HOCKEY', 'nhl/Conference=Western, Division=Pacific, Team=Vegas Golden Knights', 'VEGAS_GOLDEN_KNIGHTS_NHL'),

-- MLS Eastern Conference
('atlanta_united_mls', 'Atlanta United FC', 'Atlanta', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Atlanta United FC', 'ATLANTA_UNITED_FC_MLS'),
('cf_montreal_mls', 'CF Montreal', 'Montreal', 'MLS', 'SOCCER', 'mls/Conference=East, Team=CF Montreal', 'CF_MONTREAL_MLS'),
('charlotte_fc_mls', 'Charlotte FC', 'Charlotte', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Charlotte FC', 'CHARLOTTE_FC_MLS'),
('chicago_fire_mls', 'Chicago Fire FC', 'Chicago', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Chicago Fire FC', 'CHICAGO_FIRE_FC_MLS'),
('columbus_crew_mls', 'Columbus Crew', 'Columbus', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Columbus Crew', 'COLUMBUS_CREW_MLS'),
('dc_united_mls', 'D.C. United', 'Washington', 'MLS', 'SOCCER', 'mls/Conference=East, Team=D.C. United', 'DC_UNITED_MLS'),
('fc_cincinnati_mls', 'FC Cincinnati', 'Cincinnati', 'MLS', 'SOCCER', 'mls/Conference=East, Team=FC Cincinnati', 'FC_CINCINNATI_MLS'),
('inter_miami_mls', 'Inter Miami CF', 'Miami', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Inter Miami CF', 'INTER_MIAMI_CF_MLS'),
('nashville_sc_mls', 'Nashville SC', 'Nashville', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Nashville SC', 'NASHVILLE_SC_MLS'),
('new_england_revolution_mls', 'New England Revolution', 'New England', 'MLS', 'SOCCER', 'mls/Conference=East, Team=New England Revolution', 'NEW_ENGLAND_REVOLUTION_MLS'),
('nycfc_mls', 'New York City FC', 'New York', 'MLS', 'SOCCER', 'mls/Conference=East, Team=New York City FC', 'NEW_YORK_CITY_FC_MLS'),
('red_bulls_mls', 'New York Red Bulls', 'New York', 'MLS', 'SOCCER', 'mls/Conference=East, Team=New York Red Bulls', 'NEW_YORK_RED_BULLS_MLS'),
('orlando_city_mls', 'Orlando City SC', 'Orlando', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Orlando City SC', 'ORLANDO_CITY_SC_MLS'),
('philadelphia_union_mls', 'Philadelphia Union', 'Philadelphia', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Philadelphia Union', 'PHILADELPHIA_UNION_MLS'),
('toronto_fc_mls', 'Toronto FC', 'Toronto', 'MLS', 'SOCCER', 'mls/Conference=East, Team=Toronto FC', 'TORONTO_FC_MLS'),
-- MLS Western Conference
('austin_fc_mls', 'Austin FC', 'Austin', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Austin FC', 'AUSTIN_FC_MLS'),
('colorado_rapids_mls', 'Colorado Rapids', 'Colorado', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Colorado Rapids', 'COLORADO_RAPIDS_MLS'),
('fc_dallas_mls', 'FC Dallas', 'Dallas', 'MLS', 'SOCCER', 'mls/Conference=West, Team=FC Dallas', 'FC_DALLAS_MLS'),
('houston_dynamo_mls', 'Houston Dynamo FC', 'Houston', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Houston Dynamo FC', 'HOUSTON_DYNAMO_FC_MLS'),
('lafc_mls', 'LAFC', 'Los Angeles', 'MLS', 'SOCCER', 'mls/Conference=West, Team=LA FC', 'LAFC_MLS'),
('la_galaxy_mls', 'LA Galaxy', 'Los Angeles', 'MLS', 'SOCCER', 'mls/Conference=West, Team=LA Galaxy', 'LA_GALAXY_MLS'),
('minnesota_united_mls', 'Minnesota United FC', 'Minnesota', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Minnesota United FC', 'MINNESOTA_UNITED_FC_MLS'),
('portland_timbers_mls', 'Portland Timbers', 'Portland', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Portland Timbers', 'PORTLAND_TIMBERS_MLS'),
('real_salt_lake_mls', 'Real Salt Lake', 'Salt Lake City', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Real Salt Lake', 'REAL_SALT_LAKE_MLS'),
('san_jose_earthquakes_mls', 'San Jose Earthquakes', 'San Jose', 'MLS', 'SOCCER', 'mls/Conference=West, Team=San Jose Earthquakes', 'SAN_JOSE_EARTHQUAKES_MLS'),
('seattle_sounders_mls', 'Seattle Sounders FC', 'Seattle', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Seattle Sounders FC', 'SEATTLE_SOUNDERS_FC_MLS'),
('sporting_kc_mls', 'Sporting Kansas City', 'Kansas City', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Sporting Kansas City', 'SPORTING_KANSAS_CITY_MLS'),
('stl_city_mls', 'St. Louis City SC', 'St. Louis', 'MLS', 'SOCCER', 'mls/Conference=West, Team=St. Louis City SC', 'ST_LOUIS_CITY_SC_MLS'),
('vancouver_whitecaps_mls', 'Vancouver Whitecaps FC', 'Vancouver', 'MLS', 'SOCCER', 'mls/Conference=West, Team=Vancouver Whitecaps FC', 'VANCOUVER_WHITECAPS_FC_MLS');