// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxcezmqaknhftwnpkanu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4Y2V6bXFha25oZnR3bnBrYW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NTQzMTAsImV4cCI6MjA4NTIzMDMxMH0.PCwY79dY7iBhSuq6z55tpXTtGLsNpki2aUpugQjQBms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});